version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn anytask.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/anytask/static
      - media_volume:/home/app/web/anytask/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/anytask/static
      - media_volume:/home/app/web/anytask/media
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  mysql_data:
  static_volume:
  media_volume:

